329
215
645
403
326
50.7701
299
245
424
393
320
45.0674
315
315
535
407
604
54.3258
363
209
624
497
302
52.02
589
243
565
403
274
54.0298
323
301
396
391
304
47.4323
391
233
639
395
280
53.1359
429
275
448
445
508
59.1807
345
257
604
437
448
54.3061
423
237
516
765
286
57.7127
429
231
436
507
426
49.7306
357
249
771
559
342
57.2229
439
261
619
407
274
54.4783
357
221
534
661
322
56.6166
393
261
412
429
337
50.3226
315
243
763
543
454
62.2386
325
251
632
515
428
56.289
523
287
420
454
294
51.0569
339
255
726
544
432
59.9317
333
355
697
415
306
51.3884
461
209
536
489
272
53.3743
339
225
614
469
292
48.1937
353
205
588
471
376
50.401
477
257
406
778
418
58.2745
335
239
615
547
320
54.7647
571
223
428
691
406
63.8926
319
231
569
427
286
46.3738
327
253
472
563
274
49.1351
323
237
683
521
278
55.6771
477
263
438
527
446
60.7498
335
331
590
487
272
53.4478
325
245
552
449
286
48.9401
457
247
762
435
476
58.4994
369
227
614
535
294
54.8932
359
249
456
575
402
56.4852
347
235
466
723
374
55.2161
327
251
548
455
298
50.8374
335
253
627
531
328
57.4244
507
201
585
415
252
51.9679
335
235
703
427
382
55.345
497
237
620
419
270
53.9656
339
247
474
429
312
49.1035
363
257
454
721
392
58.323
397
759
422
507
297
63.4731
585
285
411
407
312
53.0583
359
239
482
465
278
43.5133
341
255
639
563
272
51.9877
373
233
725
439
416
56.9227
331
245
692
640
328
56.1034
419
229
706
459
352
56.5676
375
263
430
435
315
47.2644
309
247
374
399
307
44.7886
345
245
516
407
448
54.2832
401
257
628
407
298
51.4147
347
249
426
567
378
53.1737
357
223
464
561
306
50.7658
361
263
542
417
330
49.2376
337
225
726
497
276
51.8364
343
249
561
431
288
48.9659
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 4) >= this->size() (which is 4)
407
299
548
605
296
54.3668
327
257
412
391
314
45.674
321
207
550
437
276
43.2401
351
327
684
433
354
50.3123
423
217
746
419
392
58.8931
321
241
432
419
284
46.4306
443
219
720
487
388
60.863
381
247
697
485
336
57.4818
389
231
436
411
393
44.6124
351
233
432
445
290
45.002
311
215
586
563
302
47.9006
331
235
526
491
338
51.9411
299
233
378
401
304
44.7013
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 4) >= this->size() (which is 4)
335
233
628
421
298
49.8468
335
253
658
623
384
55.8322
335
287
418
503
350
45.7394
363
247
652
491
382
56.3524
351
197
458
511
306
49.9376
433
235
600
433
422
54.6928
323
233
424
523
322
48.5573
347
241
580
467
320
56.9412
339
239
400
401
278
48.3141
341
239
656
429
340
54.485
345
213
661
445
380
52.6408
385
279
603
429
416
53.7946
311
257
383
401
278
47.2896
381
267
397
411
298
51.2713
329
265
382
581
272
50.1462
351
255
698
443
364
56.5033
355
223
637
399
390
53.2261
371
247
631
685
270
56.6894
383
257
553
461
292
52.067
335
299
714
543
294
54.595
345
213
608
461
274
46.9785
359
241
732
563
398
62.0588
347
239
644
433
282
51.9652
313
255
440
415
326
48.95
483
247
550
441
453
59.4255
345
251
492
694
375
61.4757
